---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager-visibility
  labels:
    name: alertmanager-visibility
  namespace: kube-visibility
spec:
  jobLabel: alertmanager
  namespaceSelector:
    matchNames:
      - kube-visibility
  endpoints:
    - interval: 30s
      port: web
  selector:
    matchLabels:
      alertmanager: visibility
