apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ApiServer.yaml
- ControllerManager.yaml
- CoreDNS.yaml
- KubeScheduler.yaml
- Kubelet.yaml
- alertmanager.yaml
- grafana.yaml
- prometheus.yaml
