---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: prometheus
spec:
  selector:
    matchLabels:
      prometheus: visibility
  endpoints:
    - interval: 30s
      port: web
