---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-visibility
  labels:
    name: prometheus-visibility
spec:
  jobLabel: prometheus
  namespaceSelector:
    matchNames:
      - kube-visibility
  endpoints:
    - interval: 30s
      port: web
  selector:
    matchLabels:
      prometheus: visibility
