---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-kube-visibility
  labels:
    alertmanager: kube-visibility
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - name: web
      port: 9093
      targetPort: web
  selector:
    alertmanager: kube-visibility
    app: kube-visibility
