---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-visibility
  labels:
    prometheus: kube-visibility
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: NodePort
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: kube-visibility
    app: prometheus
