---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-visibility
resources:
  - namespace.yaml
bases:
  - ./node_exporter
  - ./kube-state-metrics
  - ./prometheus-operator
  - ./prometheus
  # - ./grafana
commonAnnotations:
  kube-visibility.modifier: "k8s-1.15"
