---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  labels:
    app.kubernetes.io/version: 1.8.0
  namespace: kube-visibility
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 1.8.0
    spec:
      containers:
        - name: kube-state-metrics
          image: quay.io/coreos/kube-state-metrics:v1.8.0
