apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 1.9.5
  name: kube-state-metrics
  namespace: kube-visibility
spec:
  clusterIP: None
  ports:
    - name: https-metrics
      port: 8080
      targetPort: https-metrics
    - name: https-telemetry
      port: 8081
      targetPort: https-telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics
