---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager-visibility
  labels:
    name: alertmanager-visibility
    kube-visibility.monitoring: "enabled" # this enable the prometheus scrapping
  namespace: kube-visibility
spec:
  jobLabel: alertmanager
  namespaceSelector:
    matchNames:
      - kube-visibility
  selector:
    matchLabels:
      alertmanager: visibility
  endpoints:
    - port: web
      interval: 30s
