---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-visibility
  labels:
    name: prometheus-visibility
    kube-visibility.monitoring: "enabled" # this enable the prometheus scrapping
  namespace: kube-visibility
spec:
  jobLabel: prometheus
  selector:
    matchLabels:
      prometheus: visibility
  namespaceSelector:
    matchNames:
      - kube-visibility
  endpoints:
    - interval: 30s
      port: web
