---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-visibility
commonLabels:
  environment: minikube
bases:
  - ../../../../base/kube-state-metrics
patches:
  - cluster-role-binding-patch.yaml
  - cluster-role-patch.yaml
  - role-binding-patch.yaml
  - role-patch.yaml
  - service-account-patch.yaml
  - service-patch.yaml
  - statefulset-patch.yaml